---
title: Technotrumpet.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Matthew Green, tech enthusiast
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"
excerpt_separator: <!--more-->
